### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by KardiWeb** [utdemir/furby#2]
Hello dear developer!

Furby demonstration (demo) available?

Thank you!

**Comment by utdemir** [comment]
Hey, this was a pretty old project of mine and I wasn't using it; but I just created project website on GitHub.

Now you can see an example at: http://utdemir.com/furby/

**Comment by KardiWeb** [comment]
Super!
You do not upgrade yet? Since then you modified the code? If so then you might ask?

**Comment by utdemir** [comment]
The "feedzirra" renamed to "feedjira" since then, I had to fix some stuff; I'll update the code this evening.

**Comment by KardiWeb** [comment]
Excellent! Thank you very much! I look forward to. :)

**Comment by utdemir** [comment]
Hey, I'm sorry for acting late.

I just committed [my changes](https://github.com/utdemir/furby/commit/5fa39b7ed0ae1cd2bdac3dcda1e3ce60c54225ef).

Let me know if anything is broken.
