### ISSUE TITLE
Feedjira install error

### ISSUE THREAD

**Issue by ghost** [utdemir/furby#3]
Hello dear developer!

`gem install feedjira
Building native extensions.  This could take a while...
ERROR:  Error installing feedjira:
    ERROR: Failed to build gem native extension.

```
/usr/bin/ruby -r ./siteconf20150922-9952-ecfdjo.rb extconf.rb
```

mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /usr/local/lib64/gems/ruby/nokogiri-1.6.6.2/gem_make.out
`

**Comment by ghost** [comment]
And starting:

./furby.rb feeds template.erb output.html
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- feedjira (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in`require'
    from ./furby.rb:7:in `<main>'

**Comment by utdemir** [comment]
You probably need development headers for ruby installed, try searching a package like `ruby-dev` on your distribution.

Also, try to use `bundler` for installing dependencies for furby. A simple Google search will suffice for some tutorials on `bundler`.

**Comment by ghost** [comment]
Openshift tested not working furby app :(

**Comment by utdemir** [comment]
@KardiWeb , can you post the error message and the commands you gave?
